### ISSUE TITLE
VIM: choice of the API

### ISSUE THREAD

**Issue by jpaillard** [mind-inria/hidimstat#17]
There is currently inconsistencies between the API used for different variable importance methods (loco is a function, cpi is a class).

I suggest to use the following template:
```
- VimMethod (fitted_estimator)
  - fit(X, y=None)
    * for CPI fit the imputation models
    * for LOCO fit the clone models on subsets of the data
  - predict(X, y-None)
    * Return prediction for the perturbed models
  - score(X, y)
    * Compute the variable importance 
```

In addition to the issue #14 which aimed at separating the fit of the main estimator from the rest, this issue separates the scoring which fits better the scikit-learn API, allowing to test different scoring approaches like the robust-CPI suggested by @AngelReyero

**Comment by bthirion** [comment]
I'm wondering whether we should have 2 estimators for CPI: one for imputation and one for prediction.

**Comment by jpaillard** [comment]
Yes, sorry for the imprecision but CPI would actually take as argument both a `fitted_estimator` and a `imputation_model`

**Comment by bthirion** [comment]
@achamma723 any advice from you is welcome.

**Comment by achamma723** [comment]
Hello @bthirion and @jpaillard,
CPI was introduced before as the second block of the full pipeline of the BBI package (I think Joseph meant the BBI as the class because cpi is mainly located in the compute_importance file). Now, as you decided to further elaborate the idea of the fit/compute importance idea, it will make more sense IMO to have a similar idea of packaging where there is a path for fitting the inference learner and a path of choices for the importance function to launch.

**Comment by bthirion** [comment]
Sklearn-compatible learners I guess. What else do you have in mind ? Pytorch learners ?
